### ISSUE TITLE
visual issues

### ISSUE THREAD

**Issue by normalamron** [CapnKitten/Spotify-Discord#15]
![Capture](https://user-images.githubusercontent.com/47062844/94920661-63872d00-04bf-11eb-9fc1-9d55f2d2428f.PNG)

I use AdjustableServerWidth and Inside the red line it says "new", it overflows whenever I choose the theme, but it gets fit when I close and open the AdjustableServerWidth theme also Could you extend the server list to the blue area, this may not be suitable for Spotify theme but I believe it will look nice.

**Comment by CapnKitten** [comment]
The Spotify Discord theme has a fixed width for the servers container, so any other theme that changes it will override whichever theme is enabled first. To "fix" this issue, just enable AdjustableServerWidth after enabling Spotify Discord.

As for extending the server list, it's intentionally like that because prior to Discord adding the public servers button, the add/create server button was fixed there.
